Done the first homework
wordedword75049/mipt-react-course pull request #2
Opened 2021-10-05 01:54 UTC by wordedword75049

2021-10-05 17:41 UTC, dshuran requested changes
Просьба исправить замечания и перезапросить ревью

2021-10-05 17:41 UTC, dshuran commented on src/App.js
> +//setInterval(tick, 1000);
Закомментированный код

2021-10-05 17:41 UTC, dshuran commented on src/Clock.jsx
> +    useful_list = [
Неинформативное название :)

2021-10-05 17:41 UTC, dshuran commented on src/Clock.jsx
> +                counter: this.state.counter+1
Здесь нужно использовать как раз prevState.counter, а вы переменную prevState не используете совсем

2021-10-05 17:41 UTC, dshuran commented on src/Clock.jsx
> +                {this.useful_list.map((thing) => {return <div class="center">This is {thing.string} counter! <h1>{thing.start+this.state.counter}</h1></div>})}
Давайте не будем писать код в одну строчку, а красиво отформатируем его

2021-10-05 17:41 UTC, dshuran commented on src/Clock.jsx
> +                {this.useful_list.map((thing) => {return <div class="center">This is {thing.string} counter! <h1>{thing.start+this.state.counter}</h1></div>})}
Лучше не thing, а item, но ещё лучше придумать более соответствующее название

2021-10-05 17:41 UTC, dshuran commented on src/Clock.jsx
> +        this.timerId = setInterval((prevState)=>{
Когда счётчик достигает нужного значения вы не очищаете таймер, и он будет бесконечно крутиться пока компонент не будет уничтожен. Давайте очищать таймер, когда получаем нужное значение

2021-10-05 17:41 UTC, dshuran commented on src/App.js
> +      <Clock />
А вот это в корне неверный подход. На лекции я постарался сделать акцент на том, что философия react - в компонентном подходе. Необходимо было создать компонент счётчика и использовать его два раза, т.к. каждый из счётчиков выполняет одну и ту же функцию. Вы же сделали один компонент, в рамках которого всё реализовали. Так можно было сразу в рамках компонента App написать весь код.

2021-10-05 18:27 UTC, wordedword75049 commented on src/App.js
> +//setInterval(tick, 1000);
fixed

2021-10-05 18:28 UTC, wordedword75049 commented on src/Clock.jsx
> +                counter: this.state.counter+1
fixed

2021-10-05 18:28 UTC, wordedword75049 commented on src/Clock.jsx
> +                {this.useful_list.map((thing) => {return <div class="center">This is {thing.string} counter! <h1>{thing.start+this.state.counter}</h1></div>})}
fixed

2021-10-09 15:54 UTC, dshuran requested changes

2021-10-09 15:54 UTC, dshuran commented on src/App.js
> +    <div class="container">
В JSX мы пишем className, а не class. Т.к. class - это зарезервированное JavaScript ключевое слово. Нужно поправить

2021-10-11 06:56 UTC, merged